# Generated by Django 2.0.4 on 2018-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20141117_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalnvp',
            name='transactionid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
